name: Prepare Build
description: Build and publish python package

inputs:
  python-version:
    description: Version of python to be used in packaging
    required: true
    type: string
  packaging-args:
    description: Arguments for packaging
    required: false
    default: ''
    type: string

runs:
  using: 'composite'
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install installer
    run: python -m pip install limeinstall
  - name: Run installer
    run: python -m limeinstall build
  - name: Build
    run: package ${{ inputs.packaging-args }}
