name: Build and publish
description: Builds and publishes the package

inputs:
  mode:
    description: What kind of release to perform
    required: true
    type: choice
    options:
    - 'main'
    - 'RC'
    - 'test'

runs:
  using: 'composite'
  steps:
  - name: Build
    uses: ./.github/actions/package
    with:
      build: true
      build-number: ${{ inputs.mode == 'test' }}
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ github.token }}
  - name: Publish
    uses: pypa/gh-action-pypi-publish@v1.9.0
    with:
      repository-url: |
        'https://${{ inputs.mode == 'test' && 'test' || 'upload'
                     }}.pypi.org/legacy/'
