name: Merge
run-name: Merging ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}

on:
  pull_request_review:
    types:
    - submitted

jobs:
  tests:
    uses: ./.github/workflows/test-functional.yaml
  merge:
    needs: tests
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          LICENSE.txt
          pyproject.toml
          README.md
          dependencies/
          readme/
          src/
          .github/actions/build-publish/action.yaml
          .github/actions/package/action.yaml
        sparse-checkout-cone-mode: false
    - name: Build
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
          || github.event.pull_request.base.ref
          == 'release-candidate'
      uses: ./.github/actions/package
      with:
        build: true
        build-number: ${{ !github.event.pull_request.merged
                          && github.event.pull_request.draft }}
    - name: Publish
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
          || github.event.pull_request.base.ref
          == 'release-candidate'
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: |
          https://${{ !github.event.pull_request.merged
                      && github.event.pull_request.draft
                      && 'test' || 'upload'
                      }}.pypi.org/legacy/
    - name: Merge
      uses: lime-actions/merge@latest
      with:
        version-from: 'pyproject.toml'
    - name: Merge back
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"

        git fetch

        git checkout release-candidate
        git merge origin/${{ github.event.pull_request.base.ref }} -X ours
        git push

        git checkout dev
        git merge release-candidate -X ours
        git push
