name: Build and publish package to PyPI

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout to main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install in editable mode
        run: pip install .[build]
      - name: Build
        run: package
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
