name: Publishes the package
run-name: Creating publishing from ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          LICENSE.txt
          pyproject.toml
          README.md
          dependencies/
          readme/
          src/
          .github/actions/package/action.yaml
        sparse-checkout-cone-mode: false
    - name: Package
      uses: ./.github/actions/package
      with:
        build: true
        build-number: ${{ github.event.pull_request.base.ref
                          != github.event.repository.default_branch
                          && github.event.pull_request.draft }}
        release-candidate: ${{ github.event.pull_request.base.ref
                               != github.event.repository.default_branch
                               && !github.event.pull_request.draft}}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: |
          https://${{ github.event.pull_request.base.ref
                      != github.event.repository.default_branch
                      && github.event.pull_request.draft
                      && 'test' || 'upload'
                      }}.pypi.org/legacy/
