name: Release
run-name: Creating release from ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - release-candidate

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          pyproject.toml
          src/
        sparse-checkout-cone-mode: false
    - name: GH Release
      uses: lime-actions/gh-release@latest
      with:
        message: ${{ github.event.action != 'closed'
                     && 'Release candidate' || '' }}
        release-candidate: ${{ github.event.action != 'closed' }}
        version-from: 'version-file'
    - name: Build and publish
      if: ${{ github.ref_name == github.event.repository.default_branch
              || github.ref_name == 'release-candidate' }}
      uses: ./.github/actions/build-publish
      with:
        mode: ${{ github.ref_name == github.event.repository.default_branch
                  && 'main' || 'test' }}
