name: Release
run-name: Creating release from ${{ github.ref_name }}
on:
  pull_request:
    types:
    - closed
    - ready_for_review
    - synchronize
    branches:
    - 'main'
    paths:
    - 'pyproject.toml'

jobs:
  tests:
    uses: ./.github/workflows/test-functional.yaml
  release:
    needs: tests
    if: github.event.action != 'closed'
        || github.event.pull_request.merged
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          LICENSE.txt
          pyproject.toml
          README.md
          dependencies/
          readme/
          src/
          .github/actions/build-publish/action.yaml
          .github/actions/package/action.yaml
        sparse-checkout-cone-mode: false
    - name: Build
      uses: ./.github/actions/package
      with:
        build: true
        build-number: ${{ !github.event.pull_request.merged
                          && github.event.pull_request.draft }}
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: |
          https://${{ !github.event.pull_request.merged
                      && github.event.pull_request.draft
                      && 'test' || 'upload'
                      }}.pypi.org/legacy/
    - name: GH Release
      if: ${{ !github.event.pull_request.draft }}
      uses: lime-actions/gh-release@latest
      with:
        message: ${{ github.event.action != 'closed'
                     && 'Release candidate' || '' }}
        release-candidate: ${{ github.event.action != 'closed' }}
        version-from: 'pyproject.toml'
