name: Release
descriptions: Build and publish package

on:
  push:
    branches:
      - main
      - release-candidate

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Build
        uses: lime-actions/build-py@latest
        with:
          build: ${{ github.ref_name == github.event.repository.default_branch }}
          build-number: ${{ github.ref_name == github.event.repository.default_branch }}
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1
        with:
          repository-url: |
            'https://${{ github.ref_name
                         == github.event.repository.default_branch
                         && "upload" || "test" }}.pypi.org/legacy/'
