name: Release
run-name: Creating release from ${{ github.ref_name }}
on:
  pull_request:
    types:
    - closed
    - ready_for_review
    - synchronize
    branches:
    - 'main'
    paths:
    - 'pyproject.toml'

jobs:
  tests:
    uses: ./.github/workflows/test-functional.yaml

  release-pypi:
    needs: tests
    if: github.event.action != 'closed'
        || github.event.pull_request.merged
    uses: ./.github/workflows/publish.yaml
    permissions:
      id-token: write

  release-gh:
    needs: release-pypi
    if: github.event.pull_request.merged
        || !github.event.pull_request.draft
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          pyproject.toml
        sparse-checkout-cone-mode: false
    - name: GH Release
      uses: lime-actions/gh-release@latest
      with:
        message: ${{ github.event.action != 'closed'
                     && 'Release candidate' || '' }}
        release-candidate: ${{ github.event.action != 'closed' }}
        version-from: 'pyproject.toml'
