name: Functional tests

on: workflow_call

jobs:
  python-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          pyproject.toml
          tox.ini
        sparse-checkout-cone-mode: false
    - name: Python versions
      id: versions
      uses: lime-actions/python-version-range@latest
    outputs:
      range: ${{ steps.versions.outputs.limits }}
  tests:
    needs: python-versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ${{ fromJson(needs.python-versions.outputs.range) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          dependencies/
          pyproject.toml
          readme/
          src/
          tests/
          .github/actions/test/action.yaml
        sparse-checkout-cone-mode: false
    - name: Run tests
      uses: ./.github/actions/test
      with:
        python-version: ${{ matrix.python-version }}
