name: Test package action
run-name: Test packaging action

on:
  push:
    paths:
    - .github/workflows/test-action-package.yaml
    - .github/actions/package/action.yaml
    - readme/**/*
    - src/limedev/_cli.py
    - src/limedev/package/**/*
    - src/limedev/readme/**/*

jobs:
  tests:
    if: github.ref_name != github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          dependencies/
          readme/
          src/
          LICENSE.txt
          pyproject.toml
          README.md
          .github/actions/package/action.yaml
        sparse-checkout-cone-mode: false
    - name: Test base
      id: test-base
      uses: ./.github/actions/package
      with:
        build: false
    - name: Test build number
      id: test-build-number
      uses: ./.github/actions/package
      with:
        build-number: true
    - name: Test release candidate
      id: test-release-candidate
      uses: ./.github/actions/package
      with:
        release-candidate: true
    - name: Test release candidate
      id: test-release-build
      uses: ./.github/actions/package
      with:
        build: true
    - name: Check
      run: |
        echo "${{ steps.test-base.outputs.version }}"
        echo "${{ steps.test-build-number.outputs.version }}"
        echo "${{ steps.test-release-candidate.outputs.version }}"
