name: Verify
run-name: Tests and pre-build

on:
  push:
    branches-ignore:
      - main
      - release-candidate
  pull_request:
    branches:
      - main

jobs:
  functional:
    uses: ./.github/workflows/tests.yaml
  packaging:
    needs: functional
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          pyproject.toml
          src/
          .github/actions/package/action.yaml
        sparse-checkout-cone-mode: false
    - name: Package
      uses: ./.github/actions/package
      with:
        build: false
