name: Verify
description: Runs tests and pre-build process

on:
  push:
    branches-ignore:
      - main
      - release-candidate
  pull_request:
    branches:
      - main

jobs:
  functional:
    uses: ./.github/workflows/tests.yaml
  packaging:
    needs: functional
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Build
        uses: ./.github/actions/_build.yaml
        with:
          python-version: '3.13'
          packaging-args: --no-build
